#!/usr/bin/env bun
/**
 * The whole manual release sequence, in one process, so the tree it leaves
 * behind is correct without a human remembering a step.
 *
 * `release:manual` was `release:preflight && bumpp && bun publish --access
 * public`. Two things were missing from it, and they turn out to be the same
 * thing twice:
 *
 *   1. `bun build` INLINES `package.json` (`BUILD_VERSION` in
 *      `src/lib/update/build-info.ts` falls back to `packageJson.version`), and
 *      `bumpp` bumps that version. So every release left the COMMITTED
 *      `dist/main.js` describing the previous version and `bindings:check` red
 *      on `main` until someone regenerated by hand. Measured, same Bun 1.3.11,
 *      one bumped version: `85697a48…` at `0.3.2` vs `2e541596…` at `0.3.3`.
 *      v0.3.2 and v0.4.0 were both rebuilt by hand after the fact.
 *   2. Nothing asserted a clean working tree, so an unrelated in-flight edit
 *      could be swept into the release commit and shipped under the tag.
 *
 * WHY A WRAPPER RATHER THAN JUST `bumpp -x`. `bumpp`'s execute hook is the right
 * PLACE for the rebuild — it runs after `updateFiles` and before `gitCommit`
 * (`versionBump()` in `bumpp/dist/shared/*.mjs`), which is the only window where
 * the new version is on disk and the commit has not happened yet. But `-x` alone
 * is not sufficient, because of how `bumpp` commits. Its default `gitCommit` is:
 *
 *     git commit --allow-empty --message <msg> <the files bumpp itself updated>
 *
 * That is git's PATHSPEC form, and `git commit <pathspec>` deliberately IGNORES
 * THE INDEX for every other path. So a hook that does the documented fix —
 * `git add -f dist/main.js` — has its work silently dropped from the release
 * commit and left dangling after it, which is the exact state this file exists
 * to prevent. Measured on a throwaway repo, staging `dist/main.js` and then
 * committing `bumpp`-style:
 *
 *     A: git commit -m … package.json     → git show HEAD:dist/main.js = v1  (stale)
 *                                           git status              = `M  dist/main.js`
 *     B: git commit -m … --all            → git show HEAD:dist/main.js = v2  (correct)
 *                                           git status              = clean
 *
 * `--all` is what makes `bumpp` commit the INDEX rather than a pathspec, so the
 * hook's `git add -f` lands. (`-a` stages tracked modifications ON TOP OF the
 * index; anything already added — including a brand-new content-hash chunk that
 * `-a` would never have picked up on its own — stays.)
 *
 * AND `--all` IS EXACTLY WHAT DISABLES `bumpp`'S OWN CLEAN-TREE CHECK. From its
 * CLI:
 *
 *     if (!options.all && !options.noGitCheck) await checkGitStatus()
 *
 * — and `noGitCheck` defaults to `true` regardless, so `bumpp` checks nothing
 * today and would check nothing under the flag the rebuild needs. The rebuild
 * fix and the clean-tree guard are therefore not two independent chores: turning
 * on the first removes the only backstop that could have supplied the second.
 * Something has to own the ordering — guard, then pin, then bump, then publish —
 * and a `&&` chain in `package.json` cannot express "guard the tree that the
 * step after next is allowed to modify". Hence this file.
 *
 * WHAT COUNTS AS CLEAN, AND WHY (see `cleanTreeObjection`). Blocking: every
 * TRACKED modification, staged or unstaged, including `dist/`. Non-blocking:
 * untracked files.
 *
 *   - Tracked, including `dist/`: `git commit --all` sweeps every tracked
 *     modification into the release commit, so those bytes ship under the tag
 *     with no gate having seen them. `dist/` is force-tracked against
 *     `.gitignore`, so a hand-edited or half-built `dist/` is a tracked
 *     modification like any other — and `bindings:check` reads the INDEX, not
 *     the working tree, so it is structurally blind to it. This guard is the
 *     only thing in the repo that looks.
 *   - It does not fight the rebuild, because of WHERE it runs: the guard is step
 *     one of this file, and the rebuild happens later, inside `bumpp`'s execute
 *     hook. By the time `dist/` is touched the guard has already passed. The
 *     guard's demand is "`dist/` matched `HEAD` when we started", which is true
 *     of every tree the previous release left behind.
 *   - Untracked files do NOT block. The mechanism being guarded is `git commit
 *     --all`, which stages only tracked paths; an untracked file cannot reach
 *     the release commit by any route in this flow. Blocking on one would fail
 *     the release for a scratch note or an editor artifact — a false positive on
 *     a path whose next step is irreversible. They are listed as a note instead,
 *     so a releaser who expected a file to ship finds out before the tag rather
 *     than after. (Ignored files are not listed by `git status --porcelain` at
 *     all, so nothing under an untouched `dist/` shows up here.)
 *
 * THE REBUILD USES `process.execPath`, NEVER A BARE `bun` — the trap
 * `scripts/ops/prepack.ts` documents, re-measured for the `bun run` path this
 * script is launched through:
 *
 *     $ ~/.bun/bin/bun run probe        # outer interpreter: 1.3.11, the pin
 *     execPath      : /opt/homebrew/Cellar/bun/1.3.10/bin/bun
 *     versions.bun  : 1.3.14
 *
 * i.e. invoking the pinned binary and letting the script say `bun` gets you the
 * developer's Bun, and `bun build`'s output is a function of the Bun version. So
 * the rebuild goes through `prepack()`, which bundles with `process.execPath` —
 * the same binary whose `process.versions.bun` was checked, with no PATH lookup
 * in between. For the same reason the execute hook is spawned as
 * `"<process.execPath>" "<this file>" --rebuild` rather than `bun run …`:
 * `bumpp` spawns it with the ambient PATH, so naming the binary is the only way
 * to know which one bundles.
 *
 * THE PIN ASSERTION STILL MEASURES THE RIGHT PROCESS. `release:preflight`'s
 * guarantee was that it is launched by the same bare `bun` that `prepack` will
 * later get; this file is launched the same way (`bun run release:manual`), so
 * asserting on its own `process.versions.bun` is the identical measurement. It
 * delegates to `prepack({ checkOnly: true })` so the refusal text stays in one
 * place.
 *
 * WHAT IS STAGED comes from `check-bindings.ts`'s `ARTIFACTS`, not a literal
 * list, so the set this stages cannot drift from the set `bindings:check`
 * verifies. `-f` is not optional: `dist/` is gitignored, so a bare `git add`
 * silently skips a NEW file (a renamed content-hash chunk).
 *
 * Usage:
 *   bun run release:manual                    # guard, pin, bump+rebuild, publish
 *   bun run release:manual --no-publish       # stop after the tag is pushed
 *   bun run release:manual -- --release patch -y   # anything else goes to bumpp
 *   bun scripts/ops/release.ts --rebuild      # just rebuild + stage dist/
 *
 * Exit codes: 0 ok · 1 refused (dirty tree, or the running Bun is not the pin) ·
 * 2 a step failed. Nothing irreversible happens on 1: the refusals are both
 * ahead of `bumpp`, which is where the commit, the tag and the push are.
 *
 * `git` and every child process go through the two injectable runners this repo
 * already uses (`check-bindings.ts`'s `GitRunner`, `prepack.ts`'s
 * `CommandRunner`), so the tests run offline without a bundler, a repository or
 * a registry.
 */

import { ARTIFACTS, type GitRunner, realGit } from "./check-bindings"
import { type CommandRunner, prepack, type PrepackOptions, realRunner } from "./prepack"

// Every child process — `git`, `bumpp`, `bun publish` — runs through the two
// runners imported above, both of which already resolve the repo root from
// their own file, so this script works from any cwd without repeating it.

/** Runs only the rebuild-and-stage step. What `bumpp`'s execute hook invokes. */
export const REBUILD_FLAG = "--rebuild"

/** Cut the tag, skip the registry. Every release so far has shipped this way. */
export const NO_PUBLISH_FLAG = "--no-publish"

/** This script's own flags, which must never be forwarded to `bumpp`. */
export const OWN_FLAGS: ReadonlyArray<string> = [REBUILD_FLAG, NO_PUBLISH_FLAG]

/** `bun publish`'s argv, argv-identical to the tail of the old `release:manual`. */
export const PUBLISH_ARGV: ReadonlyArray<string> = ["publish", "--access", "public"]

// --- what gets staged ---

/**
 * The committed, generated paths the release commit must carry — read from the
 * gate that verifies them, so the two cannot disagree. `dist/lib`, `dist/main.js`.
 */
export function stagePathspecs(artifacts: ReadonlyArray<{ id: string }> = ARTIFACTS): Array<string> {
  return artifacts.map((artifact) => artifact.id)
}

/** `-f` because `dist/` is gitignored and a bare `git add` skips new files there. */
export function stageArgv(pathspecs: ReadonlyArray<string> = stagePathspecs()): Array<string> {
  return ["add", "-f", "--", ...pathspecs]
}

// --- the clean-tree guard ---

/** One `git status --porcelain` record, split into its status code and its path. */
export interface StatusRecord {
  /** The two-character XY code. `??` is untracked. */
  code: string
  path: string
}

/**
 * Parse `git status --porcelain` (v1). Paths containing a newline are quoted by
 * git in this format, so splitting on newlines cannot cut a record in half.
 */
export function parseStatus(porcelain: string): Array<StatusRecord> {
  const records: Array<StatusRecord> = []
  for (const line of porcelain.split("\n")) {
    if (line.length < 4) continue
    records.push({ code: line.slice(0, 2), path: line.slice(3) })
  }
  return records
}

/** Untracked, and therefore unreachable by `git commit --all`. */
function isUntracked(record: StatusRecord): boolean {
  return record.code === "??"
}

/**
 * Why this working tree must not be released from, or `undefined` if it may.
 *
 * Only tracked modifications block — see the header for why untracked files do
 * not, and why `dist/` is deliberately NOT exempted even though the rebuild
 * step is about to write to it.
 */
export function cleanTreeObjection(porcelain: string): string | undefined {
  const dirty = parseStatus(porcelain).filter((record) => !isUntracked(record))
  if (dirty.length === 0) return undefined
  return (
    `release: REFUSING to release from a dirty working tree.\n`
    + `\n`
    + `  ${dirty.length} tracked file(s) differ from HEAD:\n`
    + `\n`
    + dirty.map((record) => `    ${record.code} ${record.path}`).join("\n")
    + `\n`
    + `\n`
    + `The release commit is made with \`git commit --all\` so that the regenerated\n`
    + `dist/ lands inside it, which means every tracked modification above would be\n`
    + `swept in and shipped under the tag — reviewed by nobody, and unpickable\n`
    + `afterwards, because a published tag must not be moved.\n`
    + `\n`
    + `Commit them, or park them, and start again:\n`
    + `    git status\n`
    + `    git stash --include-untracked      # NOT in a shared worktree — see AGENTS.md\n`
  )
}

/** Untracked files are reported, not refused, so a missing file is noticed early. */
export function untrackedNote(porcelain: string): string | undefined {
  const untracked = parseStatus(porcelain).filter(isUntracked)
  if (untracked.length === 0) return undefined
  return (
    `release: ${untracked.length} untracked file(s) will NOT be part of this release:\n`
    + untracked.map((record) => `    ${record.path}`).join("\n")
  )
}

// --- the execute hook ---

/**
 * The command string handed to `bumpp -x`. Both paths are quoted because
 * `bumpp` tokenizes this with `args-tokenizer` before spawning, and a home
 * directory with a space in it would otherwise split into two argv entries.
 */
export function executeCommand(bun: string, script: string): string {
  return `"${bun}" "${script}" ${REBUILD_FLAG}`
}

/**
 * `bumpp`'s argv. `--all` is load-bearing twice over — see the header: it is
 * what makes the commit carry the index (and therefore the staged rebuild), and
 * it is what disables `bumpp`'s own clean-tree check, which is why this file
 * runs its own first.
 *
 * `bumpp` moved out of `package.json`'s scripts and into this string, which is
 * why it is in knip's `ignoreDependencies`: knip reads binaries out of script
 * strings and cannot follow one into an array literal in TypeScript.
 */
export function bumppArgv(execute: string, extra: ReadonlyArray<string> = []): Array<string> {
  return ["x", "bumpp", "--all", "--execute", execute, ...extra]
}

// --- steps ---

/**
 * The pin inputs `prepack` reads from the environment, overridable so the tests
 * never depend on the Bun they happen to be running under (`check:ops` runs
 * off-pin routinely). Forwarded verbatim, and only when present: `prepack`
 * distinguishes "no `running` given, go measure" from "`running` is
 * `undefined`, i.e. not Bun at all" by key presence.
 */
export type PinOptions = Pick<PrepackOptions, "running" | "pinned" | "root">

function pinOptions(options: PinOptions): PinOptions {
  const pin: PinOptions = {}
  if ("running" in options) pin.running = options.running
  if (options.pinned !== undefined) pin.pinned = options.pinned
  if (options.root !== undefined) pin.root = options.root
  return pin
}

export interface RebuildOptions extends PinOptions {
  git?: GitRunner
  run?: CommandRunner
  log?: (line: string) => void
  pathspecs?: ReadonlyArray<string>
}

/**
 * Rebuild the committed artifacts against the version that is now on disk and
 * stage them. Runs INSIDE `bumpp`, between the bump and the commit.
 *
 * `prepack()` is the rebuild rather than a local reimplementation: it is already
 * the argv-identical pair of builds (`build` + `build:lib`), it already refuses
 * off-pin before writing anything, and it already bundles with
 * `process.execPath`.
 */
export function rebuildAndStage(options: RebuildOptions = {}): number {
  const log = options.log ?? ((line: string) => { console.error(line) })
  const git = options.git ?? realGit
  const pathspecs = options.pathspecs ?? stagePathspecs()

  const built = prepack({ ...pinOptions(options), run: options.run, log })
  if (built !== 0) return built

  const staged = git(stageArgv(pathspecs))
  if (staged.status !== 0) {
    log(`release: could not stage ${pathspecs.join(", ")} — ${staged.stderr.trim() || `git exited ${staged.status}`}`)
    return 2
  }
  log(`release: rebuilt and staged ${pathspecs.join(", ")}`)
  return 0
}

export interface ReleaseOptions extends PinOptions {
  git?: GitRunner
  run?: CommandRunner
  log?: (line: string) => void
  /** The interpreter the execute hook will bundle with. Never a PATH lookup. */
  bun?: string
  /** This file, as `bumpp` will have to spawn it. */
  script?: string
  /** Extra argv forwarded to `bumpp`. */
  bumppArgs?: ReadonlyArray<string>
  publish?: boolean
}

/**
 * Guard, assert, bump, publish. The order is the point: everything that can
 * refuse runs before `bumpp`, because `bumpp` commits, tags AND pushes, and the
 * runbook is explicit that a published tag must not be moved.
 *
 * The tree comes first because it is the failure nothing else in the repo
 * catches; the pin is re-asserted at `prepack` time on the publish path anyway.
 */
export function release(options: ReleaseOptions = {}): number {
  const log = options.log ?? ((line: string) => { console.error(line) })
  const git = options.git ?? realGit
  const run = options.run ?? realRunner
  const bun = options.bun ?? process.execPath
  const script = options.script ?? import.meta.path

  const status = git(["status", "--porcelain"])
  if (status.status !== 0) {
    log(`release: could not read the working tree — ${status.stderr.trim() || `git exited ${status.status}`}`)
    return 2
  }
  const objection = cleanTreeObjection(status.stdout)
  if (objection !== undefined) {
    log(objection)
    return 1
  }
  const note = untrackedNote(status.stdout)
  if (note !== undefined) log(note)

  const pinned = prepack({ ...pinOptions(options), checkOnly: true, run, log })
  if (pinned !== 0) return pinned

  const bumped = run(bun, bumppArgv(executeCommand(bun, script), options.bumppArgs ?? []))
  if (bumped.status !== 0) {
    log(`release: bumpp exited ${bumped.status}${bumped.output ? ` — ${bumped.output.trim()}` : ""}`)
    return 2
  }

  if (options.publish === false) {
    log("release: --no-publish — the tag is cut and pushed; nothing was published.")
    return 0
  }

  const published = run(bun, PUBLISH_ARGV)
  if (published.status !== 0) {
    log(`release: \`bun publish\` exited ${published.status}${published.output ? ` — ${published.output.trim()}` : ""}`)
    return 2
  }
  return 0
}

// --- entry point ---

export function main(
  argv: ReadonlyArray<string> = process.argv.slice(2),
  options: ReleaseOptions & RebuildOptions = {},
): number {
  if (argv.includes(REBUILD_FLAG)) return rebuildAndStage(options)
  return release({
    ...options,
    publish: options.publish ?? !argv.includes(NO_PUBLISH_FLAG),
    bumppArgs: options.bumppArgs ?? argv.filter((arg) => !OWN_FLAGS.includes(arg)),
  })
}

if (import.meta.main) {
  process.exit(main())
}
