#!/usr/bin/env bun
/**
 * The whole manual release sequence, in one process, so the tree it leaves
 * behind is correct without a human remembering a step.
 *
 * `release:manual` was `release:preflight && bumpp && bun publish --access
 * public`. Two things were missing from it, and they turn out to be the same
 * thing twice:
 *
 *   1. `bun build` INLINES `package.json` (`BUILD_VERSION` in
 *      `src/lib/update/build-info.ts` falls back to `packageJson.version`), and
 *      `bumpp` bumps that version. So every release left the COMMITTED
 *      `dist/main.js` describing the previous version and `bindings:check` red
 *      on `main` until someone regenerated by hand. Measured, same Bun 1.3.11,
 *      one bumped version: `85697a48…` at `0.3.2` vs `2e541596…` at `0.3.3`.
 *      v0.3.2 and v0.4.0 were both rebuilt by hand after the fact.
 *   2. Nothing asserted a clean working tree, so an unrelated in-flight edit
 *      could be swept into the release commit and shipped under the tag.
 *
 * A third thing was missing, and it is the same thing a third time: the
 * CHANGELOG entry. The runbook used to say "generate the block with
 * `release:notes vX.Y.Z` and paste it into `CHANGELOG.md`" and then, in the very
 * next step, "run `release:manual`" — whose FIRST action is the clean-tree guard
 * above, which refuses any tracked modification, the freshly pasted changelog
 * included. Step 3 guaranteed step 4 would refuse. v0.4.1 was cut around it by
 * committing the changelog separately first, which is why its history carries
 * two commits where every release before it carries one. So this file writes the
 * entry itself: the tag is an argument to it, `release-notes.ts` is a sibling,
 * and `CHANGELOG.md` carries an insertion anchor put there for exactly this.
 * The guard keeps its zero exemptions — see WHERE THE CHANGELOG IS WRITTEN.
 *
 * WHY A WRAPPER RATHER THAN JUST `bumpp -x`. `bumpp`'s execute hook is the right
 * PLACE for the rebuild — it runs after `updateFiles` and before `gitCommit`
 * (`versionBump()` in `bumpp/dist/shared/*.mjs`), which is the only window where
 * the new version is on disk and the commit has not happened yet. But `-x` alone
 * is not sufficient, because of how `bumpp` commits. Its default `gitCommit` is:
 *
 *     git commit --allow-empty --message <msg> <the files bumpp itself updated>
 *
 * That is git's PATHSPEC form, and `git commit <pathspec>` deliberately IGNORES
 * THE INDEX for every other path. So a hook that does the documented fix —
 * `git add -f dist/main.js` — has its work silently dropped from the release
 * commit and left dangling after it, which is the exact state this file exists
 * to prevent. Measured on a throwaway repo, staging `dist/main.js` and then
 * committing `bumpp`-style:
 *
 *     A: git commit -m … package.json     → git show HEAD:dist/main.js = v1  (stale)
 *                                           git status              = `M  dist/main.js`
 *     B: git commit -m … --all            → git show HEAD:dist/main.js = v2  (correct)
 *                                           git status              = clean
 *
 * `--all` is what makes `bumpp` commit the INDEX rather than a pathspec, so the
 * hook's `git add -f` lands. (`-a` stages tracked modifications ON TOP OF the
 * index; anything already added — including a brand-new content-hash chunk that
 * `-a` would never have picked up on its own — stays.)
 *
 * AND `--all` IS EXACTLY WHAT DISABLES `bumpp`'S OWN CLEAN-TREE CHECK. From its
 * CLI:
 *
 *     if (!options.all && !options.noGitCheck) await checkGitStatus()
 *
 * — and `noGitCheck` defaults to `true` regardless, so `bumpp` checks nothing
 * today and would check nothing under the flag the rebuild needs. The rebuild
 * fix and the clean-tree guard are therefore not two independent chores: turning
 * on the first removes the only backstop that could have supplied the second.
 * Something has to own the ordering — guard, then pin, then bump, then publish —
 * and a `&&` chain in `package.json` cannot express "guard the tree that the
 * step after next is allowed to modify". Hence this file.
 *
 * WHAT COUNTS AS CLEAN, AND WHY (see `cleanTreeObjection`). Blocking: every
 * TRACKED modification, staged or unstaged, including `dist/`. Non-blocking:
 * untracked files.
 *
 *   - Tracked, including `dist/`: `git commit --all` sweeps every tracked
 *     modification into the release commit, so those bytes ship under the tag
 *     with no gate having seen them. `dist/` is force-tracked against
 *     `.gitignore`, so a hand-edited or half-built `dist/` is a tracked
 *     modification like any other — and `bindings:check` reads the INDEX, not
 *     the working tree, so it is structurally blind to it. This guard is the
 *     only thing in the repo that looks.
 *   - It does not fight the rebuild, because of WHERE it runs: the guard is step
 *     one of this file, and the rebuild happens later, inside `bumpp`'s execute
 *     hook. By the time `dist/` is touched the guard has already passed. The
 *     guard's demand is "`dist/` matched `HEAD` when we started", which is true
 *     of every tree the previous release left behind.
 *   - Untracked files do NOT block. The mechanism being guarded is `git commit
 *     --all`, which stages only tracked paths; an untracked file cannot reach
 *     the release commit by any route in this flow. Blocking on one would fail
 *     the release for a scratch note or an editor artifact — a false positive on
 *     a path whose next step is irreversible. They are listed as a note instead,
 *     so a releaser who expected a file to ship finds out before the tag rather
 *     than after. (Ignored files are not listed by `git status --porcelain` at
 *     all, so nothing under an untouched `dist/` shows up here.)
 *
 * WHY THE TAG IS AN ARGUMENT NOW (`release:manual vX.Y.Z`). The changelog block
 * is generated from the GitHub milestone whose title IS the tag, so the notes
 * cannot be fetched — and a bad milestone cannot be refused — until the version
 * is known. Letting `bumpp` prompt for it would push both after the bump. The
 * milestone model already decides the tag in advance (`release:check milestone
 * vX.Y.Z`, `release:notes vX.Y.Z`), so naming it once more here takes nothing
 * away, and the version reaches `bumpp` as `--release X.Y.Z`, which makes gate 3
 * — "the tag matches `package.json`" — true by construction rather than by a
 * preflight anyone can skip. That is the failure `v0.1.1` shipped.
 *
 * WHERE THE CHANGELOG IS WRITTEN, AND WHY IT IS NOT AN EXEMPTION. The block is
 * FETCHED, VALIDATED AND RENDERED before `bumpp` — so a milestone that
 * `release:notes` would refuse to emit for (missing, empty, an unparseable PR
 * title, an unmerged PR) refuses the whole release at exit 1, with the tree
 * still exactly as the guard found it. It is WRITTEN inside `bumpp`'s execute
 * hook, beside the rebuild, for the same reason the rebuild is there: that is
 * the only window where the commit has not happened yet, and `git commit --all`
 * is about to sweep the working tree into it. The hook therefore produces
 * everything the release commit carries beyond the version bump itself.
 *
 * Two consequences worth stating, because both are the point:
 *
 *   - The guard is untouched and still has NO exemptions. `CHANGELOG.md` is
 *     dirty for the same reason `dist/` is: this script dirtied it, after the
 *     guard, deliberately. The guard only ever asked "did the tree match HEAD
 *     when we started".
 *   - Nothing is written on any refusal path, and nothing is written before the
 *     `bumpp` confirmation prompt. Declining that prompt (`process.exit(1)` in
 *     `bumpp`'s CLI) or hitting Ctrl-C leaves the tree clean, so the next
 *     attempt is not blocked by the leftovers of the last one — which is the
 *     failure mode of pasting the block by hand, mechanised.
 *
 * The rendered block reaches the hook through the environment
 * (`MAXIMAL_RELEASE_CHANGELOG_BLOCK`), because the hook is a separate process
 * `bumpp` spawns with the ambient environment. A temp file would work too and
 * costs an untracked artefact in the one flow that reports untracked files. With
 * the variable unset — a by-hand `release.ts --rebuild` — the hook rebuilds and
 * stages `dist/` and touches no markdown, exactly as it did before.
 *
 * THAT HANDOVER DEPENDS ON `realRunner` PASSING `env` EXPLICITLY, and it did not
 * until this change. Bun's `spawnSync` defaults the child's environment to the
 * SNAPSHOT the process started with, not to the current `process.env`, so a
 * variable set at runtime is dropped without a word. Measured, Bun 1.3.11:
 *
 *     process.env.PROBE = "set-by-parent"
 *     spawnSync(bun, ["-e", …])                        → PROBE undefined
 *     spawnSync(bun, ["-e", …], { env: process.env })  → PROBE set-by-parent
 *
 * Caught in a scratch clone, where the first end-to-end release came out green
 * with no changelog entry in the commit. `prepack.ts`'s `realRunner` now names
 * `env`, and `prepack.test.ts` pins it — it is the one test in that suite that
 * spawns anything, because the failure it prevents is silent and green.
 *
 * AN ENTRY THAT IS ALREADY THERE IS LEFT ALONE. If `CHANGELOG.md` already has a
 * `## X.Y.Z` heading for the version being cut — a re-run, or a human who pasted
 * it — the changelog step is skipped in full, including the `gh` reads. It is
 * reported, not refused: the entry the release needs exists, and rewriting
 * somebody's hand-edited block (or appending a second one) is the only outcome
 * worse than leaving it.
 *
 * THE REBUILD USES `process.execPath`, NEVER A BARE `bun` — the trap
 * `scripts/ops/prepack.ts` documents, re-measured for the `bun run` path this
 * script is launched through:
 *
 *     $ ~/.bun/bin/bun run probe        # outer interpreter: 1.3.11, the pin
 *     execPath      : /opt/homebrew/Cellar/bun/1.3.10/bin/bun
 *     versions.bun  : 1.3.14
 *
 * i.e. invoking the pinned binary and letting the script say `bun` gets you the
 * developer's Bun, and `bun build`'s output is a function of the Bun version. So
 * the rebuild goes through `prepack()`, which bundles with `process.execPath` —
 * the same binary whose `process.versions.bun` was checked, with no PATH lookup
 * in between. For the same reason the execute hook is spawned as
 * `"<process.execPath>" "<this file>" --rebuild` rather than `bun run …`:
 * `bumpp` spawns it with the ambient PATH, so naming the binary is the only way
 * to know which one bundles.
 *
 * THE PIN ASSERTION STILL MEASURES THE RIGHT PROCESS. `release:preflight`'s
 * guarantee was that it is launched by the same bare `bun` that `prepack` will
 * later get; this file is launched the same way (`bun run release:manual`), so
 * asserting on its own `process.versions.bun` is the identical measurement. It
 * delegates to `prepack({ checkOnly: true })` so the refusal text stays in one
 * place.
 *
 * WHAT IS STAGED comes from `check-bindings.ts`'s `ARTIFACTS`, not a literal
 * list, so the set this stages cannot drift from the set `bindings:check`
 * verifies. `-f` is not optional: `dist/` is gitignored, so a bare `git add`
 * silently skips a NEW file (a renamed content-hash chunk).
 *
 * Usage:
 *   bun run release:manual vX.Y.Z                  # guard, pin, notes, bump+rebuild, publish
 *   bun run release:manual vX.Y.Z --no-publish     # stop after the tag is pushed
 *   bun run release:manual vX.Y.Z -y               # anything else goes to bumpp
 *   bun scripts/ops/release.ts --rebuild           # just rebuild + stage dist/
 *
 * Exit codes: 0 ok · 1 refused (no tag, dirty tree, the running Bun is not the
 * pin, a tag that already exists or is not ahead of every tag that does, a PR
 * still open in the milestone being cut, or a milestone the notes cannot be
 * generated from) · 2 a step failed, including a gate that could not READ what
 * it compares against. Nothing irreversible happens on 1 or 2: every refusal is
 * ahead of `bumpp`, which is where the commit, the tag and the push are.
 *
 * TWO OF THOSE REFUSALS ARE `release-gates.ts`, CALLED FROM HERE. Gate 4 (the
 * tag is ahead of every tag that exists, local AND remote) and gate 5 (nothing
 * that claims to ship in this release is still open) are both checks about the
 * instant the tag is cut, so a preflight a human runs and a workflow that fires
 * on tag push are respectively skippable and too late. `release()` is the last
 * place either can still be free. See `evaluateTagOrder` and `evaluateOpenPrs`.
 *
 * `git` and every child process go through the two injectable runners this repo
 * already uses (`check-bindings.ts`'s `GitRunner`, `prepack.ts`'s
 * `CommandRunner`), the GitHub reads go through `release-notes.ts`'s `GhRunner`,
 * and `CHANGELOG.md` is read and written through an injected pair — so the tests
 * run offline without a bundler, a repository, a registry or a working copy.
 */

import fs from "node:fs"
import path from "node:path"

import { ARTIFACTS, type GitRunner, realGit } from "./check-bindings"
import { type CommandRunner, prepack, type PrepackOptions, realRunner } from "./prepack"
import {
  collectOpenPrGate,
  collectTagOrderGate,
  exitCodeFor as gateExitCodeFor,
  type GateReport,
  renderFindings,
} from "./release-gates"
import {
  collectReleaseNotes,
  exitCodeFor,
  type GhRunner,
  type ReleaseNotes,
  renderChangelog,
  renderProblems,
  stripV,
} from "./release-notes"

// Every child process — `git`, `bumpp`, `bun publish` — runs through the two
// runners imported above, both of which already resolve the repo root from
// their own file, so this script works from any cwd without repeating it.
// `CHANGELOG.md` is the one path this file resolves itself.
const REPO_ROOT = path.resolve(import.meta.dir, "..", "..")

/** Runs only the rebuild-and-stage step. What `bumpp`'s execute hook invokes. */
export const REBUILD_FLAG = "--rebuild"

/** Cut the tag, skip the registry. Every release so far has shipped this way. */
export const NO_PUBLISH_FLAG = "--no-publish"

/** This script's own flags, which must never be forwarded to `bumpp`. */
export const OWN_FLAGS: ReadonlyArray<string> = [REBUILD_FLAG, NO_PUBLISH_FLAG]

/** `bun publish`'s argv, argv-identical to the tail of the old `release:manual`. */
export const PUBLISH_ARGV: ReadonlyArray<string> = ["publish", "--access", "public"]

/** The tag this release cuts. Prereleases are not modelled anywhere in this tooling. */
export const TAG_RE = /^v\d+\.\d+\.\d+$/u

// --- the changelog ---

/** The file the generated block is inserted into. */
export const CHANGELOG_FILE = "CHANGELOG.md"

/**
 * The insertion point. `CHANGELOG.md` carries this comment so automation never
 * has to guess an offset into a file whose preamble is prose. Matched by prefix,
 * not by its full text, so the sentence after it stays editable.
 */
export const CHANGELOG_ANCHOR = /^<!-- releases below.*$/mu

/**
 * How the rendered block reaches `bumpp`'s execute hook, which is a separate
 * process spawned with the ambient environment. Unset means "rebuild only",
 * which is what a by-hand `release.ts --rebuild` gets.
 */
export const CHANGELOG_ENV = "MAXIMAL_RELEASE_CHANGELOG_BLOCK"

/**
 * Does the file already document this version? Both heading shapes
 * `release-notes.ts` can emit count: `## [0.4.2](compare-link) (date)` and the
 * unlinked `## 0.4.2 (date)` a first release gets.
 */
export function changelogHasVersion(source: string, version: string): boolean {
  const escaped = version.replaceAll(".", "\\.")
  return new RegExp(`^## (?:\\[${escaped}\\]|${escaped}[ (])`, "mu").test(source)
}

/**
 * Insert `block` directly below the anchor, or `undefined` when the anchor is
 * gone. One blank line separates it from the release under it, which is the
 * spacing every existing pair in the file already uses — so the diff of a
 * generated insert is indistinguishable from the pasted ones above it.
 */
export function insertChangelogBlock(source: string, block: string): string | undefined {
  const match = CHANGELOG_ANCHOR.exec(source)
  if (!match) return undefined
  const at = match.index + match[0].length
  const head = source.slice(0, at)
  const tail = source.slice(at)
  const entry = block.trimEnd()
  if (tail.trim() === "") return `${head}\n\n${entry}\n`
  return `${head}\n\n${entry}${tail.replace(/^\n*/u, "\n\n")}`
}

/** Read/write seam for `CHANGELOG.md`, so no test needs a working copy. */
export interface ChangelogIo {
  read?: () => string
  write?: (contents: string) => void
}

function readChangelog(io: ChangelogIo): () => string {
  return io.read ?? (() => fs.readFileSync(path.join(REPO_ROOT, CHANGELOG_FILE), "utf8"))
}

function anchorObjection(): string {
  return (
    `release: REFUSING — ${CHANGELOG_FILE} has no insertion anchor.\n`
    + `\n`
    + `  Expected a line beginning \`<!-- releases below\`, which is what tells this\n`
    + `  script where a generated block goes without guessing an offset.\n`
    + `\n`
    + `Put the anchor back above the newest release heading, or paste the block by\n`
    + `hand and re-run — an entry that is already there is left alone:\n`
    + `    bun run release:notes <tag>\n`
  )
}

/** What the changelog step decided. Exactly one of these three fields is set. */
export interface ChangelogPlan {
  /** The block to insert, when there is one to insert. */
  block?: string
  /** Why the release must not proceed. */
  objection?: string
  /** Why there is nothing to do, when that is the answer. */
  note?: string
}

export interface ChangelogPlanOptions extends ChangelogIo {
  tag: string
  gh?: GhRunner
  now?: () => Date
}

/**
 * Fetch, validate and render the entry for `tag` — everything about the
 * changelog that can fail, done BEFORE `bumpp` so a failure costs nothing.
 *
 * The refusal condition is `release:notes`'s own: this returns an objection for
 * anything that would make it exit non-zero and write nothing. A release whose
 * notes cannot be trusted is a release that must not be cut, and there is
 * deliberately no `--force` here — `release:notes --force` emits the well-formed
 * subset for a human to paste, which this step then finds and leaves alone.
 */
export function planChangelog(options: ChangelogPlanOptions): ChangelogPlan {
  let source: string
  try {
    source = readChangelog(options)()
  } catch (err) {
    return { objection: `release: could not read ${CHANGELOG_FILE} — ${err instanceof Error ? err.message : String(err)}` }
  }
  if (!CHANGELOG_ANCHOR.test(source)) return { objection: anchorObjection() }

  const version = stripV(options.tag)
  if (changelogHasVersion(source, version)) {
    return { note: `release: ${CHANGELOG_FILE} already documents ${version} — leaving it exactly as it is.` }
  }

  let notes: ReleaseNotes
  try {
    notes = collectReleaseNotes({ tag: options.tag, gh: options.gh, now: options.now })
  } catch (err) {
    return {
      objection:
        `release: REFUSING — could not generate the ${CHANGELOG_FILE} entry for ${options.tag}.\n`
        + `\n  ${err instanceof Error ? err.message : String(err)}\n`,
    }
  }

  if (exitCodeFor(notes) !== 0) {
    return {
      objection:
        `${renderProblems(notes.problems)}\n`
        + `\n`
        + `release: REFUSING — the milestone \`${options.tag}\` cannot produce trustworthy\n`
        + `notes, and the entry is the only thing that reaches the changelog. Fix the\n`
        + `milestone, or paste a block by hand and re-run:\n`
        + `    bun run release:notes ${options.tag} --force\n`,
    }
  }
  return { block: renderChangelog(notes) }
}

/**
 * Write the block into `CHANGELOG.md`. Runs INSIDE `bumpp`, between the bump and
 * the commit, so `git commit --all` picks it up. Returns an objection or
 * `undefined`; everything that could realistically fail here was already checked
 * by `planChangelog` before the bump.
 */
export function applyChangelog(block: string, io: ChangelogIo = {}): string | undefined {
  const write = io.write ?? ((contents: string) => { fs.writeFileSync(path.join(REPO_ROOT, CHANGELOG_FILE), contents) })
  let source: string
  try {
    source = readChangelog(io)()
  } catch (err) {
    return `release: could not read ${CHANGELOG_FILE} — ${err instanceof Error ? err.message : String(err)}`
  }
  const next = insertChangelogBlock(source, block)
  if (next === undefined) return anchorObjection()
  try {
    write(next)
  } catch (err) {
    return `release: could not write ${CHANGELOG_FILE} — ${err instanceof Error ? err.message : String(err)}`
  }
  return undefined
}

// --- what gets staged ---

/**
 * The committed, generated paths the release commit must carry — read from the
 * gate that verifies them, so the two cannot disagree. `dist/lib`, `dist/main.js`.
 */
export function stagePathspecs(artifacts: ReadonlyArray<{ id: string }> = ARTIFACTS): Array<string> {
  return artifacts.map((artifact) => artifact.id)
}

/** `-f` because `dist/` is gitignored and a bare `git add` skips new files there. */
export function stageArgv(pathspecs: ReadonlyArray<string> = stagePathspecs()): Array<string> {
  return ["add", "-f", "--", ...pathspecs]
}

// --- the clean-tree guard ---

/** One `git status --porcelain` record, split into its status code and its path. */
export interface StatusRecord {
  /** The two-character XY code. `??` is untracked. */
  code: string
  path: string
}

/**
 * Parse `git status --porcelain` (v1). Paths containing a newline are quoted by
 * git in this format, so splitting on newlines cannot cut a record in half.
 */
export function parseStatus(porcelain: string): Array<StatusRecord> {
  const records: Array<StatusRecord> = []
  for (const line of porcelain.split("\n")) {
    if (line.length < 4) continue
    records.push({ code: line.slice(0, 2), path: line.slice(3) })
  }
  return records
}

/** Untracked, and therefore unreachable by `git commit --all`. */
function isUntracked(record: StatusRecord): boolean {
  return record.code === "??"
}

/**
 * Why this working tree must not be released from, or `undefined` if it may.
 *
 * Only tracked modifications block — see the header for why untracked files do
 * not, and why `dist/` is deliberately NOT exempted even though the rebuild
 * step is about to write to it.
 */
export function cleanTreeObjection(porcelain: string): string | undefined {
  const dirty = parseStatus(porcelain).filter((record) => !isUntracked(record))
  if (dirty.length === 0) return undefined
  return (
    `release: REFUSING to release from a dirty working tree.\n`
    + `\n`
    + `  ${dirty.length} tracked file(s) differ from HEAD:\n`
    + `\n`
    + dirty.map((record) => `    ${record.code} ${record.path}`).join("\n")
    + `\n`
    + `\n`
    + `The release commit is made with \`git commit --all\` so that the regenerated\n`
    + `dist/ lands inside it, which means every tracked modification above would be\n`
    + `swept in and shipped under the tag — reviewed by nobody, and unpickable\n`
    + `afterwards, because a published tag must not be moved.\n`
    + `\n`
    + `Commit them, or park them, and start again:\n`
    + `    git status\n`
    + `    git stash --include-untracked      # NOT in a shared worktree — see AGENTS.md\n`
  )
}

/** Untracked files are reported, not refused, so a missing file is noticed early. */
export function untrackedNote(porcelain: string): string | undefined {
  const untracked = parseStatus(porcelain).filter(isUntracked)
  if (untracked.length === 0) return undefined
  return (
    `release: ${untracked.length} untracked file(s) will NOT be part of this release:\n`
    + untracked.map((record) => `    ${record.path}`).join("\n")
  )
}

// --- the gates that must precede `bumpp` ---

/**
 * Run one `release-gates.ts` gate here, where a refusal is still free, and map
 * its report onto this script's exit codes: 0 ok · 1 refused · 2 could not run.
 *
 * `release-gates.ts` says a caller MUST treat 2 as non-blocking, because a gate
 * that fails closed on its own bugs takes the repo down with it. That argument
 * is about CI, where the cost of a false red is a wedged repository. Here the
 * trade is inverted and so is the answer: a refusal costs a re-run, a false PASS
 * costs a tag that must never be moved. So a gate that cannot run stops the
 * release — and it can only ever stop it BEFORE `bumpp`, which is the only
 * reason it is legitimate to fail closed at all.
 */
export function runGate(
  collect: () => GateReport,
  log: (line: string) => void,
  cannotRun: string,
): number {
  let report: GateReport
  try {
    report = collect()
  } catch (err) {
    log(`release: ${cannotRun} — ${err instanceof Error ? err.message : String(err)}`)
    return 2
  }
  log(renderFindings(report))
  if (gateExitCodeFor(report, "enforce") === 0) return 0
  log("\nrelease: REFUSING — nothing has been committed, tagged or pushed.")
  return 1
}

// --- the execute hook ---

/**
 * The command string handed to `bumpp -x`. Both paths are quoted because
 * `bumpp` tokenizes this with `args-tokenizer` before spawning, and a home
 * directory with a space in it would otherwise split into two argv entries.
 */
export function executeCommand(bun: string, script: string): string {
  return `"${bun}" "${script}" ${REBUILD_FLAG}`
}

/**
 * `bumpp`'s argv. `--all` is load-bearing twice over — see the header: it is
 * what makes the commit carry the index (and therefore the staged rebuild), and
 * it is what disables `bumpp`'s own clean-tree check, which is why this file
 * runs its own first.
 *
 * `bumpp` moved out of `package.json`'s scripts and into this string, which is
 * why it is in knip's `ignoreDependencies`: knip reads binaries out of script
 * strings and cannot follow one into an array literal in TypeScript.
 */
export function bumppArgv(execute: string, extra: ReadonlyArray<string> = []): Array<string> {
  return ["x", "bumpp", "--all", "--execute", execute, ...extra]
}

// --- steps ---

/**
 * The pin inputs `prepack` reads from the environment, overridable so the tests
 * never depend on the Bun they happen to be running under (`check:ops` runs
 * off-pin routinely). Forwarded verbatim, and only when present: `prepack`
 * distinguishes "no `running` given, go measure" from "`running` is
 * `undefined`, i.e. not Bun at all" by key presence.
 */
export type PinOptions = Pick<PrepackOptions, "running" | "pinned" | "root">

function pinOptions(options: PinOptions): PinOptions {
  const pin: PinOptions = {}
  if ("running" in options) pin.running = options.running
  if (options.pinned !== undefined) pin.pinned = options.pinned
  if (options.root !== undefined) pin.root = options.root
  return pin
}

export interface RebuildOptions extends PinOptions, ChangelogIo {
  git?: GitRunner
  run?: CommandRunner
  log?: (line: string) => void
  pathspecs?: ReadonlyArray<string>
  /** The rendered entry to insert. Handed over by `release()` via the env. */
  changelogBlock?: string
}

/**
 * Rebuild the committed artifacts against the version that is now on disk, write
 * the changelog entry, and stage both. Runs INSIDE `bumpp`, between the bump and
 * the commit — the only window where the new version is on disk and the commit
 * has not happened yet.
 *
 * `prepack()` is the rebuild rather than a local reimplementation: it is already
 * the argv-identical pair of builds (`build` + `build:lib`), it already refuses
 * off-pin before writing anything, and it already bundles with
 * `process.execPath`.
 *
 * The changelog is written LAST, after the builds have succeeded: a failed build
 * aborts `bumpp` before the commit, and the less of the tree that has been
 * touched by then the better. It is staged explicitly even though `--all` would
 * pick a tracked modification up anyway, so the hook is answerable for the whole
 * content of the release commit on its own terms.
 */
export function rebuildAndStage(options: RebuildOptions = {}): number {
  const log = options.log ?? ((line: string) => { console.error(line) })
  const git = options.git ?? realGit
  const pathspecs = options.pathspecs ?? stagePathspecs()

  const built = prepack({ ...pinOptions(options), run: options.run, log })
  if (built !== 0) return built

  const staged = git(stageArgv(pathspecs))
  if (staged.status !== 0) {
    log(`release: could not stage ${pathspecs.join(", ")} — ${staged.stderr.trim() || `git exited ${staged.status}`}`)
    return 2
  }
  log(`release: rebuilt and staged ${pathspecs.join(", ")}`)

  const block = options.changelogBlock
  if (block === undefined || block.trim() === "") return 0

  const objection = applyChangelog(block, options)
  if (objection !== undefined) {
    log(objection)
    return 2
  }
  const stagedNotes = git(["add", "--", CHANGELOG_FILE])
  if (stagedNotes.status !== 0) {
    log(`release: could not stage ${CHANGELOG_FILE} — ${stagedNotes.stderr.trim() || `git exited ${stagedNotes.status}`}`)
    return 2
  }
  log(`release: wrote and staged the ${CHANGELOG_FILE} entry`)
  return 0
}

export interface ReleaseOptions extends PinOptions, ChangelogIo {
  git?: GitRunner
  run?: CommandRunner
  gh?: GhRunner
  log?: (line: string) => void
  now?: () => Date
  /** The tag being cut — the milestone title, and the version `bumpp` bumps to. */
  tag?: string
  /** The interpreter the execute hook will bundle with. Never a PATH lookup. */
  bun?: string
  /** This file, as `bumpp` will have to spawn it. */
  script?: string
  /** Extra argv forwarded to `bumpp`. */
  bumppArgs?: ReadonlyArray<string>
  publish?: boolean
  /** The remote gate 4 reads the existing tags from. Defaults to `origin`. */
  remote?: string
  /** How the rendered block reaches the hook. Defaults to `process.env`. */
  handOverBlock?: (block: string | undefined) => void
}

/**
 * Guard, assert, generate, bump, publish. The order is the point: everything
 * that can refuse runs before `bumpp`, because `bumpp` commits, tags AND pushes,
 * and the runbook is explicit that a published tag must not be moved.
 *
 * The tree comes first because it is the failure nothing else in the repo
 * catches; the pin is re-asserted at `prepack` time on the publish path anyway;
 * then the two gates that read the world, cheapest first — gate 4 is two `git`
 * calls, gate 5 and the changelog are `gh` pipelines — and the changelog last of
 * all, because there is no point paying for it behind a refusal.
 *
 * GATE 4 IS HERE RATHER THAN IN A PREFLIGHT OR A WORKFLOW because this is the
 * last line before the tag exists. `release:check order` runs the same code for
 * the by-hand path and `--pushed` runs it as a tripwire, but both of those are
 * either skippable or too late, and a tag that has been pushed can only be
 * deleted, never corrected.
 *
 * GATE 5 IS HERE RATHER THAN LEFT TO `release:notes` because the changelog step
 * below is SKIPPED WHOLESALE — `gh` reads included — when `CHANGELOG.md` already
 * documents the version. An open PR in the milestone blocks a first attempt and
 * silently stops blocking the re-run, which is exactly when it matters.
 */
export function release(options: ReleaseOptions = {}): number {
  const log = options.log ?? ((line: string) => { console.error(line) })
  const git = options.git ?? realGit
  const run = options.run ?? realRunner
  const bun = options.bun ?? process.execPath
  const script = options.script ?? import.meta.path
  const tag = options.tag

  if (tag === undefined || !TAG_RE.test(tag)) {
    log(usage(tag))
    return 1
  }

  const status = git(["status", "--porcelain"])
  if (status.status !== 0) {
    log(`release: could not read the working tree — ${status.stderr.trim() || `git exited ${status.status}`}`)
    return 2
  }
  const objection = cleanTreeObjection(status.stdout)
  if (objection !== undefined) {
    log(objection)
    return 1
  }
  const note = untrackedNote(status.stdout)
  if (note !== undefined) log(note)

  const pinned = prepack({ ...pinOptions(options), checkOnly: true, run, log })
  if (pinned !== 0) return pinned

  const ordered = runGate(
    () => collectTagOrderGate(tag, { git, remote: options.remote }),
    log,
    "could not read the tags this release must be ahead of",
  )
  if (ordered !== 0) return ordered

  const open = runGate(
    () => collectOpenPrGate(tag, { gh: options.gh }),
    log,
    "could not read the open pull requests",
  )
  if (open !== 0) return open

  const plan = planChangelog({ tag, gh: options.gh, read: options.read, now: options.now })
  if (plan.objection !== undefined) {
    log(plan.objection)
    return 1
  }
  if (plan.note !== undefined) log(plan.note)

  const handOver = options.handOverBlock ?? ((block: string | undefined) => {
    if (block === undefined) delete process.env[CHANGELOG_ENV]
    else process.env[CHANGELOG_ENV] = block
  })

  handOver(plan.block)
  const bumppArgs = ["--release", stripV(tag), ...options.bumppArgs ?? []]
  const bumped = run(bun, bumppArgv(executeCommand(bun, script), bumppArgs))
  handOver(undefined)
  if (bumped.status !== 0) {
    log(`release: bumpp exited ${bumped.status}${bumped.output ? ` — ${bumped.output.trim()}` : ""}`)
    return 2
  }

  if (options.publish === false) {
    log("release: --no-publish — the tag is cut and pushed; nothing was published.")
    return 0
  }

  const published = run(bun, PUBLISH_ARGV)
  if (published.status !== 0) {
    log(`release: \`bun publish\` exited ${published.status}${published.output ? ` — ${published.output.trim()}` : ""}`)
    return 2
  }
  return 0
}

// --- entry point ---

/** Refusal text for a missing or malformed tag. Never a guess at what was meant. */
export function usage(given?: string): string {
  return (
    `release: REFUSING — ${given === undefined ? "no release tag was given." : `\`${given}\` is not a release tag.`}\n`
    + `\n`
    + `  usage: bun run release:manual vX.Y.Z [--no-publish] [bumpp flags]\n`
    + `\n`
    + `The tag names the GitHub milestone the CHANGELOG entry is generated from, and\n`
    + `it is what \`bumpp\` bumps package.json to, so the tag and the manifest cannot\n`
    + `disagree. Prereleases are not modelled by any of this tooling.\n`
  )
}

export interface ParsedArgv {
  tag?: string
  rebuild: boolean
  publish: boolean
  /** Everything left over, forwarded verbatim to `bumpp`. */
  bumppArgs: Array<string>
  /** Set when the argv itself is the problem. */
  objection?: string
}

/**
 * Split this script's own argv from `bumpp`'s.
 *
 * The tag is claimed positionally, but only from an item that LOOKS like a tag
 * and does not sit where a forwarded flag's value would — `-t v9.9.9` names
 * `bumpp`'s tag template, not this release. `--release` is refused outright
 * rather than forwarded: the version comes from the tag, and two sources for it
 * is exactly how `v0.1.1` was tagged off a `0.1.0` manifest.
 */
export function parseArgv(argv: ReadonlyArray<string>): ParsedArgv {
  const parsed: ParsedArgv = {
    rebuild: argv.includes(REBUILD_FLAG),
    publish: !argv.includes(NO_PUBLISH_FLAG),
    bumppArgs: [],
  }
  for (const [index, arg] of argv.entries()) {
    if (OWN_FLAGS.includes(arg)) continue
    if (arg === "--release") {
      parsed.objection =
        `release: REFUSING — \`--release\` is not forwarded.\n`
        + `\n`
        + `  The version comes from the tag: \`bun run release:manual vX.Y.Z\` bumps\n`
        + `  package.json to X.Y.Z, so the tag and the manifest cannot disagree.\n`
      return parsed
    }
    const previous = argv[index - 1]
    const couldBeAValue = previous !== undefined && previous.startsWith("-") && !OWN_FLAGS.includes(previous)
    if (parsed.tag === undefined && !couldBeAValue && TAG_RE.test(arg)) {
      parsed.tag = arg
      continue
    }
    parsed.bumppArgs.push(arg)
  }
  return parsed
}

export function main(
  argv: ReadonlyArray<string> = process.argv.slice(2),
  options: ReleaseOptions & RebuildOptions = {},
): number {
  const parsed = parseArgv(argv)
  if (parsed.rebuild) {
    return rebuildAndStage({
      ...options,
      changelogBlock: options.changelogBlock ?? process.env[CHANGELOG_ENV],
    })
  }
  if (parsed.objection !== undefined) {
    (options.log ?? ((line: string) => { console.error(line) }))(parsed.objection)
    return 1
  }
  return release({
    ...options,
    tag: options.tag ?? parsed.tag,
    publish: options.publish ?? parsed.publish,
    bumppArgs: options.bumppArgs ?? parsed.bumppArgs,
  })
}

if (import.meta.main) {
  process.exit(main())
}
