// Embed src/pages/usage-viewer.html into a TypeScript module so its
// contents survive `bun --compile` on every platform.
//
// Background: at runtime in a compiled binary, `readFileSync(URL)`
// and `Bun.file(URL).text()` against an `import.meta.url`-relative
// path both fail with ENOENT — Bun only embeds files that are
// statically reachable through `import` statements. tsdown doesn't
// honor `with { type: "text" }`, so the cleanest fix is to generate
// a plain .ts module that exports the HTML as a string and let
// tsdown bundle that normally.
//
// Run automatically as a `prebuild` step before tsdown, and also
// before `dev` so module resolution works in source mode too. The
// generated file is gitignored.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"

const ROOT = path.resolve(import.meta.dir, "..")
const HTML_PATH = path.join(ROOT, "src/pages/usage-viewer.html")
const OUT_PATH = path.join(ROOT, "src/pages/usage-viewer.gen.ts")

const html = readFileSync(HTML_PATH, "utf8")

const banner = `// AUTO-GENERATED by scripts/embed-usage-viewer.ts.
// Do not edit by hand — re-run \`bun run scripts/embed-usage-viewer.ts\`
// to refresh from src/pages/usage-viewer.html.
`

const body = `export const usageViewerHtml: string = ${JSON.stringify(html)};\n`

mkdirSync(path.dirname(OUT_PATH), { recursive: true })
writeFileSync(OUT_PATH, banner + body, "utf8")

const sizeKb = (Buffer.byteLength(html, "utf8") / 1024).toFixed(1)
console.log(`embed-usage-viewer: wrote ${OUT_PATH} (${sizeKb} KB)`)
