// Embed package.json's `version` field plus a build timestamp into
// a TypeScript module so `maximal debug` can report them after
// `bun --compile`.
//
// Background: getPackageVersion() in src/debug.ts reads
// ../package.json via fs.readFile and an `import.meta.url`-relative
// path. That fails inside a compiled binary the same way the
// usage-viewer load did — Bun only embeds files reached through
// static imports, and a bare `readFile` against a virtual-FS URL
// returns ENOENT on every platform. Result: every shipped binary
// reports `Version: unknown / Git: unknown`.
//
// Solution: at build time, snapshot the version string + the git
// SHA into src/lib/build-info.gen.ts. Plain TS module, bundles
// cleanly, survives --compile.
//
// Wired into both `bun run build` and `bun run dev` (see
// package.json), and into the binary-compile job in release.yml.

import { execSync } from "node:child_process"
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"

const ROOT = path.resolve(import.meta.dir, "..")
const PKG_PATH = path.join(ROOT, "package.json")
const OUT_PATH = path.join(ROOT, "src/lib/build-info.gen.ts")

const pkg = JSON.parse(readFileSync(PKG_PATH, "utf8")) as {
  version?: string
}
const version = pkg.version ?? "unknown"

// Honour overrides from CI — release.yml sets BUILD_VERSION to the
// stripped tag (e.g. "0.3.4") so the binary reports the release
// version even when package.json hasn't been bumped to match.
const buildVersion = process.env.BUILD_VERSION?.trim() || version

let gitSha = "unknown"
let gitBranch: string | undefined
try {
  gitSha = execSync("git rev-parse HEAD", { cwd: ROOT })
    .toString()
    .trim()
  // GITHUB_REF_NAME is set by GitHub Actions for tag/branch builds.
  // In a tag build it's e.g. "v0.3.4" — surface that as the "branch"
  // line so users see "Git: <sha> (v0.3.4)" instead of detached-head
  // shorthand.
  gitBranch =
    process.env.GITHUB_REF_NAME?.trim() ||
    (() => {
      try {
        const head = execSync("git rev-parse --abbrev-ref HEAD", { cwd: ROOT })
          .toString()
          .trim()
        return head === "HEAD" ? undefined : head
      } catch {
        return undefined
      }
    })()
} catch {
  /* git not available — leave defaults */
}

const banner = `// AUTO-GENERATED by scripts/embed-build-info.ts.
// Do not edit by hand. Re-run \`bun run scripts/embed-build-info.ts\`
// to refresh from package.json + the current git checkout.
`

const body = `export const BUILD_VERSION: string = ${JSON.stringify(buildVersion)};
export const BUILD_GIT_SHA: string = ${JSON.stringify(gitSha)};
export const BUILD_GIT_BRANCH: string | undefined = ${JSON.stringify(gitBranch)};
`

mkdirSync(path.dirname(OUT_PATH), { recursive: true })
writeFileSync(OUT_PATH, banner + body, "utf8")

const branchLabel = gitBranch ? ` (${gitBranch})` : ""
const shortSha = gitSha === "unknown" ? "unknown" : gitSha.slice(0, 7)
console.log(
  `embed-build-info: wrote ${OUT_PATH} — version=${buildVersion} git=${shortSha}${branchLabel}`,
)
